if OS.mac?
    # Taps
    tap "homebrew/cask"
    tap "homebrew/cask-fonts"

    # Fonts
    cask "font-jetbrains-mono-nerd-font"
end

tap "homebrew/core"
tap "homebrew/services"

# Shell
brew "zsh"
brew "zsh-vi-mode"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# miscs
brew "bear"             # Bear is a tool that generates a compilation database for clang tooling
brew "bob"              # Bob, A version manager for neovim
brew "curl"             # https://github.com/curl/curl
brew "direnv"
brew "eza"              # ls replacement https://github.com/eza-community/eza
brew "fd"               # modern find https://github.com/sharkdp/fd
brew "fzf"              # fuzzy-finder https://github.com/junegunn/fzf
brew "git"
brew "go"
brew "htop"
brew "lazygit"          # Terminal git GUI https://github.com/jesseduffield/lazygit
brew "mas"              # Mac automation https://github.com/mas-cli/mas
brew "npm"
brew "nvm"              # Node (JS) Version Manager https://github.com/nvm-sh/nvm
brew "pyenv"            # Python Version Manager https://github.com/pyenv/pyenv
brew "rbenv"            # Ruby Version Manager
brew "ripgrep"
brew "ruby-build"
brew "starship"
brew "stow"
brew "tmux"
brew "tldr"             # Collaborative cheatsheets for console commands https://github.com/tldr-pages/tldr
brew "yazi"
brew "zoxide"           # smarter cd command https://github.com/ajeetdsouza/zoxide

# miscs dev
brew "arduino-cli"
brew "arm-none-eabi-gcc"
brew "arm-none-eabi-gdb"
brew "docker"
brew "docker-compose"
brew "gitlab-ci-local"
brew "lazydocker"

## Casks - actual visual software 
cask "aldente"
cask "alfred"
cask "bartender"
cask "dictionaries"
cask "docker"
cask "karabiner-elements"
cask "kitty"
# cask "logi-options-plus"
cask "monitorcontrol"
cask "nikitabobko/tap/aerospace"
cask "saleae-logic"
cask "the-unarchiver"
cask "wireshark"
