db:
  excludeCommands:
    - ^ls$
    - ^la$
    - ^cd$
    - ^cd ..$
    - ^c$
    - ^clear$
    - ^exit$
    - ^vim$
    - ^nvim$

gui:
  columnLayout:
    - EXIT_CODE
    - EXECUTED_AT
    - COMMAND

  cyclicFilterModes:
    - SESSION_FILTER
    - WORKDIR_FILTER
    - SUCCESS_FILTER
    - NO_FILTER

  persistentFilterModes:
    - UNIQUE_FILTER

  theme:
    borderColor: "#3a3e4b"
    bersionFgColor: "#00e8c6"
    helpFgColor: "#606064"
    helpAccentColor: "#00e8c6"
    inputFgColor: "#d5ced9"
    filterFgColor: "#606064"
    tableCursorFgColor: "#00e8c6"
    tableCursorBgColor: "#2f323c"
    tableLabelsFgColor: "#d5ced9"

os:
  fetchCurrentSessionCmd: "tmux display-message -p '#S'"

log:
  logEnabled: false
  logLevel: DEBUG
  logFile: ~/Library/Logs/lazyhis.log
