layouts:
    - floating
    - column
    - fullscreen

select-fullscreen-layout:
    mod: mod1
    key: s

select-column-layout:
    mod: mod1
    key: d

select-floating-layout:
    mod: mod1
    key: f

relaunch-amethyst:
    mod: mod1
    key: x

# Ignore following by default
floating:
  - com.apple.systempreferences
  - com.logitech.Logi-Options
  - com.apple.ActivityMonitor
  - com.apple.finder
  - com.koingosw.alarmclockpro

# General
restore-layouts-on-launch: true
display-layout-when-changing-layouts: true
display-layout-when-changing-spaces: false
ignore-menu-bars: true

# Add 8px margin between windows
smart-window-margins: true
window-margins: true
window-margin-size: 8

